services:
  - type: web
    name: buddy-chat
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "10000"
      - key: KLIPY_API_KEY
        value: "IvQnxKXOZ682WvuFZX6knCNDXM9Xjbu6xidFZkgYx03VH7Aycc2eLRUVMxXGjGyG"
      - key: DOWNLOAD_URL
        value: "https://github.com/microsoftranjit-afk/buddy-chat/releases/download/desktop-latest/Buddy-Setup.exe"
